# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://cirrus-ci.org/guide/macOS/
#   - https://cirrus-ci.org/guide/windows/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/


win_task:
  auto_cancellation: true
  name: "Windows"
  windows_container:
    image: cirrusci/windowsservercore:cmake
    ios_version: 2019
  env:
    # use $ not %...%
    CONDA_LOCATION: $USERPROFILE\miniconda3
    PATH: $CONDA_LOCATION;$CONDA_LOCATION\Library\bin;$CONDA_LOCATION\Scripts;$CONDA_LOCATION\condabin;"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx86\x86\";$PATH
    PYTHON_ARCH: 64

  choco_script:
    - choco install -y vcredist-all
    - choco install -y windows-sdk-10-version-2004-windbg
    - choco install -y miniconda3 --params="'/D:%CONDA_LOCATION%'"

  conda_script:
    - conda update -yn base conda
    - conda install --yes -c conda-forge vtk=9.0.3
    - conda list

  test_script:
    - ps: Get-Command python
    - echo %PATH%
    - dir C:\Users\ContainerAdministrator\miniconda3\Library\bin\vtkRendering*.dll
    - dir C:\
    - dir "C:\Program Files (x86)"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx86"
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\Hostx86\x86"
    - dumpbin /dependents C:\Users\ContainerAdministrator\miniconda3\Library\bin\vtkRenderingOpenGL2-9.0.dll
    - where python
    - conda list
    - python -c "from ctypes import *; cdll.LoadLibrary('C:\Users\ContainerAdministrator\miniconda3\Library\bin\vtkRenderingOpenGL2-9.0.dll')"
    - python --version
    - python -c "import vtk"
